package:
  name: gldas
  version: 0.3

source:
  path: ../

build:
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - python
    - tethys-platform
  run:
    - netcdf4
    - numpy
    - pandas
    - rasterstats
    - rasterio
    - requests
    - pyshp
    - geomatics==0.8

about:
  home: https://github.com/rileyhales/gldas
  summary: Shows time-animated maps and timeseries plots of monthly average, 1/4 degree resolution, GLDAS data sets from NASA LDAS and LIS.
  license: BSD 3-Clause License
  license_family: BSD
  license_file: ../LICENSE
  dev_url: https://gldas-data-tool.readthedocs.io

extra:
  recipe-maintainers:
    - rileyhales